#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import re
import ssl
import sys
import json
import time
import shutil
import string
import random
import subprocess
import tarfile
import urllib.request
import urllib.parse
from http.server import HTTPServer, BaseHTTPRequestHandler
from datetime import datetime
import hashlib
import threading

# ================== 全局配置 ==================
INSTALL_DIR = "/opt/frps"
CONFIG_FILE = os.path.join(INSTALL_DIR, "frps.toml")
SERVICE_NAME = "frps"
LOG_FILE = os.path.join(INSTALL_DIR, "panel_ops.log")
FRPS_LOG_FILE = "/opt/frps.log"
WEB_API_PORT = 7500
WEB_API_USER = "admin"
WEB_API_PWD = "admin8888" # 默认初始密码

# 新增：会话与认证配置
SESSIONS = {} # 存储 session_id -> {user, expire_time}
PANEL_CONFIG_FILE = os.path.join(INSTALL_DIR, ".panel_config.json")

AVAILABLE_VERSIONS = [
    "0.70.1", "0.70.0", "0.69.1", "0.69.0", "0.68.1", "0.68.0",
    "0.67.0", "0.66.0", "0.65.0", "0.64.0", "0.62.1", "0.62.0",
    "0.61.2", "0.61.1", "0.61.0", "0.60.0"
]

if not os.path.exists(INSTALL_DIR):
    try:
        os.makedirs(INSTALL_DIR, mode=0o755)
    except:
        pass

# ================== 核心逻辑函数 ==================

def log_operation(action, detail, status):
    action_map = {
        'INSTALL': '安装/重装',
        'CONFIG': '修改配置',
        'SERVICE': '服务控制'
    }
    status_map = {
        'START': '开始执行',
        'SUCCESS': '执行成功',
        'FAILED': '执行失败',
        'ROLLBACK': '配置已回滚'
    }
    cn_action = action_map.get(action, action)
    cn_status = status_map.get(status, status)
    
    try:
        with open(LOG_FILE, 'a', encoding='utf-8') as f:
            f.write("[{0}] {1} | {2} | {3}\n".format(
                datetime.now().strftime('%Y-%m-%d %H:%M:%S'), cn_action, detail, cn_status))
    except:
        pass

def run_cmd(cmd, shell=False):
    try:
        p = subprocess.Popen(cmd, shell=shell, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        out, err = p.communicate()
        return p.returncode, out.decode('utf-8', errors='ignore'), err.decode('utf-8', errors='ignore')
    except Exception as e:
        return -1, "", str(e)

def get_arch():
    try:
        code, out, _ = run_cmd(["uname", "-m"])
        machine = out.strip()
        arch_map = {
            "x86_64": "amd64", "amd64": "amd64",
            "aarch64": "arm64", "arm64": "arm64",
            "armv7l": "arm", "armv6l": "arm",
            "i386": "386", "i686": "386"
        }
        return arch_map.get(machine, machine)
    except:
        return "amd64"

def get_ip():
    try:
        code, out, _ = run_cmd(["ip", "route", "get", "8.8.8.8"])
        if code == 0:
            m = re.search(r'src\s+([0-9.]+)', out)
            if m: return m.group(1)
    except: pass
    try:
        code, out, _ = run_cmd(["hostname", "-I"])
        if code == 0: return out.strip().split()[0]
    except: pass
    return "127.0.0.1"

def get_installed_version():
    bin_path = os.path.join(INSTALL_DIR, "frps")
    if os.path.exists(bin_path) and os.access(bin_path, os.X_OK):
        try:
            code, out, _ = run_cmd([bin_path, "--version"])
            if code == 0:
                parts = out.strip().split()
                for part in parts:
                    if re.match(r'^\d+\.\d+', part):
                        return part
                return out.strip().split('\n')[0]
        except:
            pass
    return None

def is_installed():
    return get_installed_version() is not None

def get_sysctl_path():
    if os.path.exists("/bin/systemctl"): return "/bin/systemctl"
    if os.path.exists("/usr/bin/systemctl"): return "/usr/bin/systemctl"
    return "systemctl"

def get_service_status():
    sysctl = get_sysctl_path()
    code, out, _ = run_cmd([sysctl, "is-active", SERVICE_NAME])
    return out.strip() if code == 0 else "inactive"

def read_config():
    config = {'bindPort': '7000', 'vhostHTTPPort': '18080', 'vhostHTTPSPort': '18443', 'token': ''}
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
                content = f.read()
                m = re.search(r'bindPort\s*=\s*(\d+)', content)
                if m: config['bindPort'] = m.group(1)
                m = re.search(r'vhostHTTPPort\s*=\s*(\d+)', content)
                if m: config['vhostHTTPPort'] = m.group(1)
                m = re.search(r'vhostHTTPSPort\s*=\s*(\d+)', content)
                if m: config['vhostHTTPSPort'] = m.group(1)
                m = re.search(r'(?:auth\.)?token\s*=\s*"([^"]+)"', content)
                if m: config['token'] = m.group(1)
        except: pass
    return config

def write_config(bind_port, http_port, https_port, token):
    content = """# FRPS Configuration Generated by Panel
bindPort = {0}
vhostHTTPPort = {1}
vhostHTTPSPort = {2}

auth.token = "{3}"

webServer.addr = "127.0.0.1"
webServer.port = {4}
webServer.user = "{5}"
webServer.password = "{6}"

log.to = "{7}"
log.level = "info"
log.maxDays = 30
transport.maxPoolCount = 1000
""".format(bind_port, http_port, https_port, token, WEB_API_PORT, WEB_API_USER, WEB_API_PWD, FRPS_LOG_FILE)
    
    if not os.path.exists(INSTALL_DIR):
        os.makedirs(INSTALL_DIR, mode=0o755)
        
    with open(CONFIG_FILE, 'w', encoding='utf-8') as f:
        f.write(content)
    os.chmod(CONFIG_FILE, 0o644)

def setup_systemd():
    sysctl = get_sysctl_path()
    service_content = """[Unit]
Description=Frp Server Service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Restart=on-failure
RestartSec=5s
WorkingDirectory={0}
ExecStart={0}/frps -c {1}
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
""".format(INSTALL_DIR, CONFIG_FILE)
    
    svc_path = "/etc/systemd/system/{0}.service".format(SERVICE_NAME)
    with open(svc_path, 'w', encoding='utf-8') as f:
        f.write(service_content)
    run_cmd([sysctl, "daemon-reload"])
    run_cmd([sysctl, "enable", SERVICE_NAME])

def download_and_install(version):
    arch = get_arch()
    frp_name = "frp_{0}_linux_{1}".format(version, arch)
    
    urls = [
        "https://cc.guluyun.cn/https://github.com/fatedier/frp/releases/download/v{0}/{1}.tar.gz".format(version, frp_name),
        "https://github.com/fatedier/frp/releases/download/v{0}/{1}.tar.gz".format(version, frp_name)
    ]
    
    temp_dir = "/tmp/frp_web_install_{0}".format(int(time.time()))
    if os.path.exists(temp_dir): shutil.rmtree(temp_dir)
    os.makedirs(temp_dir)
    tar_path = os.path.join(temp_dir, "frp_download")
    
    ctx = None
    try:
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
    except:
        pass

    downloaded = False
    for u in urls:
        try:
            req = urllib.request.Request(u, headers={'User-Agent': 'Mozilla/5.0'})
            if ctx:
                resp = urllib.request.urlopen(req, context=ctx, timeout=60)
            else:
                resp = urllib.request.urlopen(req, timeout=60)
            
            with open(tar_path, 'wb') as out_file:
                shutil.copyfileobj(resp, out_file)
            
            if os.path.getsize(tar_path) > 1000:
                downloaded = True
                break
        except Exception as e:
            continue
            
    if not downloaded:
        return False, "下载失败，请检查网络连接或链接有效性"
        
    src_bin = None
    try:
        with tarfile.open(tar_path, "r:gz") as tar:
            tar.extractall(path=temp_dir)
    except Exception as e:
        with open(tar_path, 'rb') as f:
            header = f.read(4)
        if header == b'\x7fELF':
            src_bin = tar_path
        else:
            return False, "解压失败且非有效二进制文件"
        
    if not src_bin:
        src_bin = os.path.join(temp_dir, frp_name, "frps")
        if not os.path.exists(src_bin):
            for root, dirs, files in os.walk(temp_dir):
                if "frps" in files:
                    src_bin = os.path.join(root, "frps")
                    break
            if not os.path.exists(src_bin):
                return False, "压缩包内未找到 frps 二进制文件"
        
    if not os.path.exists(INSTALL_DIR):
        os.makedirs(INSTALL_DIR, mode=0o755)

    shutil.copy2(src_bin, os.path.join(INSTALL_DIR, "frps"))
    os.chmod(os.path.join(INSTALL_DIR, "frps"), 0o755)
    shutil.rmtree(temp_dir)
    return True, "安装成功"

def control_service(action):
    sysctl = get_sysctl_path()
    if action == 'uninstall':
        run_cmd([sysctl, "stop", SERVICE_NAME])
        run_cmd([sysctl, "disable", SERVICE_NAME])
        run_cmd(["pkill", "-9", "-f", "frps -c"])
        time.sleep(1)
        svc_file = "/etc/systemd/system/{0}.service".format(SERVICE_NAME)
        if os.path.exists(svc_file): os.remove(svc_file)
        run_cmd([sysctl, "daemon-reload"])
        if os.path.exists(INSTALL_DIR): 
            shutil.rmtree(INSTALL_DIR)
        return True, "卸载成功"
    
    if action == 'stop':
        run_cmd([sysctl, "stop", SERVICE_NAME])
        run_cmd(["pkill", "-9", "-f", "frps -c"])
        return True, "已停止"
    elif action == 'start':
        run_cmd([sysctl, "start", SERVICE_NAME])
        time.sleep(2)
        if get_service_status() == 'active': return True, "启动成功"
        return False, "启动失败，请查看系统日志"
    elif action == 'restart':
        run_cmd([sysctl, "restart", SERVICE_NAME])
        time.sleep(2)
        if get_service_status() == 'active': return True, "重启成功"
        run_cmd([sysctl, "stop", SERVICE_NAME])
        time.sleep(1)
        run_cmd([sysctl, "start", SERVICE_NAME])
        time.sleep(2)
        if get_service_status() == 'active': return True, "重启成功"
        return False, "重启失败，请查看系统日志"
    return False, "未知操作"

def get_traffic_stats():
    total_in = 0
    total_out = 0
    try:
        with open('/proc/net/dev', 'r') as f:
            lines = f.readlines()
        for line in lines[2:]:
            parts = line.split()
            if not parts: continue
            iface = parts[0].rstrip(':')
            if iface == 'lo' or iface.startswith('veth') or iface.startswith('docker') or iface.startswith('br-'):
                continue
            total_in += int(parts[1])
            total_out += int(parts[9])
    except:
        pass
    return total_in, total_out

def get_frps_logs():
    if os.path.exists(FRPS_LOG_FILE):
        try:
            with open(FRPS_LOG_FILE, 'r', encoding='utf-8', errors='ignore') as f:
                lines = f.readlines()
                return "".join(lines[-100:])
        except:
            return "无法读取日志文件"
    return "暂无 FRPS 运行日志 (可能服务未启动或日志路径配置不同)"

# ================== 新增：认证与会话管理 ==================

def load_panel_config():
    """加载面板配置（用户名和密码哈希）"""
    default_config = {
        "username": WEB_API_USER,
        "password_hash": hashlib.sha256(WEB_API_PWD.encode()).hexdigest()
    }
    if os.path.exists(PANEL_CONFIG_FILE):
        try:
            with open(PANEL_CONFIG_FILE, 'r') as f:
                config = json.load(f)
                # 确保配置完整
                if "username" in config and "password_hash" in config:
                    return config
        except:
            pass
    # 如果文件不存在或损坏，创建默认配置
    save_panel_config(default_config)
    return default_config

def save_panel_config(config):
    """保存面板配置"""
    try:
        with open(PANEL_CONFIG_FILE, 'w') as f:
            json.dump(config, f)
        os.chmod(PANEL_CONFIG_FILE, 0o600)
    except Exception as e:
        print(f"Error saving panel config: {e}")

def check_session(session_id):
    """检查会话是否有效"""
    if not session_id or session_id not in SESSIONS:
        return False
    session = SESSIONS[session_id]
    if time.time() > session['expire_time']:
        del SESSIONS[session_id]
        return False
    return True

def create_session(username):
    """创建新会话"""
    session_id = ''.join(random.choices(string.ascii_letters + string.digits, k=32))
    SESSIONS[session_id] = {
        'user': username,
        'expire_time': time.time() + 86400 # 24小时过期
    }
    return session_id

def cleanup_sessions():
    """定期清理过期会话"""
    while True:
        now = time.time()
        expired = [sid for sid, s in SESSIONS.items() if s['expire_time'] < now]
        for sid in expired:
            del SESSIONS[sid]
        time.sleep(3600) # 每小时清理一次

# ================== Web 路由与 HTML ==================

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Frps 可视化管理面板</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        body { background-color: #f4f7f6; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding-bottom: 0; font-size: 14px; }
        .navbar { background: linear-gradient(135deg, #00c6ff, #0072ff); box-shadow: 0 2px 10px rgba(0,0,0,0.1); padding: 8px 0; }
        .navbar-brand { font-size: 1.1rem; }
        .card { border: none; border-radius: 10px; box-shadow: 0 2px 8px rgba(0,0,0,0.05); transition: transform 0.2s; margin-bottom: 15px; }
        .card-body { padding: 15px; }
        .card:hover { transform: translateY(-2px); }
        .status-dot { width: 10px; height: 10px; border-radius: 50%; display: inline-block; margin-right: 6px; }
        .status-active { background-color: #28a745; box-shadow: 0 0 6px #28a745; }
        .status-inactive { background-color: #dc3545; box-shadow: 0 0 6px #dc3545; }
        .btn { font-size: 13px; padding: 5px 12px; }
        .btn-primary { background: linear-gradient(135deg, #00c6ff, #0072ff); border: none; }
        .config-val { font-family: monospace; font-weight: 600; color: #0072ff; cursor: pointer; padding: 2px 6px; border-radius: 4px; background: #eef2ff; display: inline-block; font-size: 13px; word-break: break-all; }
        .config-val:hover { background: #dbeafe; text-decoration: none; }
        #logArea, #frpsLogArea { height: 180px; overflow-y: auto; background: #1e1e1e; color: #d4d4d4; padding: 10px; border-radius: 5px; font-size: 12px; white-space: pre-wrap; font-family: 'Consolas', monospace; }
        .hidden-section { display: none; }
        .fade-in { animation: fadeIn 0.4s; }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
        footer { background: #f8f9fa; border-top: 1px solid #e9ecef; padding: 15px 0; margin-top: 20px; text-align: center; color: #6c757d; font-size: 12px; }
        footer a { color: #0072ff; text-decoration: none; }
        .traffic-box { background: #f8f9fa; border-radius: 8px; padding: 10px; }
        .traffic-val { font-size: 1.1rem; font-weight: bold; margin: 0; }
        .traffic-speed { font-size: 0.85rem; }
        .modal-header { transition: background-color 0.3s, color 0.3s; }
        
        /* 登录页面样式 */
        .login-container {
            max-width: 400px;
            margin: 100px auto;
            padding: 30px;
            background: white;
            border-radius: 10px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
        }
        .login-title {
            text-align: center;
            margin-bottom: 30px;
            color: #0072ff;
        }
    </style>
</head>
<body>

<!-- 登录界面 -->
<div id="loginPage" class="container hidden-section">
    <div class="login-container fade-in">
        <h3 class="login-title"><i class="bi bi-shield-lock"></i> FRPS 管理登录</h3>
        <div class="mb-3">
            <label class="form-label">用户名</label>
            <input type="text" id="loginUser" class="form-control" placeholder="请输入用户名">
        </div>
        <div class="mb-3">
            <label class="form-label">密码</label>
            <input type="password" id="loginPass" class="form-control" placeholder="请输入密码">
        </div>
        <button class="btn btn-primary w-100" onclick="doLogin()">登 录</button>
        <div id="loginMsg" class="text-danger mt-2 text-center small"></div>
    </div>
</div>

<!-- 主界面 -->
<div id="mainPage" class="hidden-section">
    <nav class="navbar navbar-dark mb-3">
        <div class="container">
            <span class="navbar-brand mb-0 h1"><i class="bi bi-hdd-network"></i> FRPS 管理面板</span>
            <div class="d-flex align-items-center text-white">
                <span class="small me-3">Python: {{PY_VERSION}}</span>
                <div class="dropdown">
                    <button class="btn btn-sm btn-outline-light dropdown-toggle" type="button" data-bs-toggle="dropdown">
                        <i class="bi bi-person-circle"></i> 账户
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#changePwdModal"><i class="bi bi-key"></i> 修改密码</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item text-danger" href="#" onclick="doLogout()"><i class="bi bi-box-arrow-right"></i> 退出登录</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row mb-3 fade-in">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h6 class="text-muted mb-3"><i class="bi bi-info-circle"></i> 系统状态</h6>
                        <div class="row">
                            <div class="col-md-8">
                                <div class="row">
                                    <div class="col-6 col-md-6 mb-2">
                                        <small class="text-muted">服务器 IP</small><br>
                                        <span id="sys-ip" class="config-val" onclick="copyText(this.innerText, 'IP')">-</span>
                                    </div>
                                    <div class="col-6 col-md-6 mb-2">
                                        <small class="text-muted">系统架构</small><br>
                                        <span id="sys-arch" class="config-val">-</span>
                                    </div>
                                    <div class="col-6 col-md-6 mb-2">
                                        <small class="text-muted">FRPS 版本</small><br>
                                        <span id="sys-ver" class="config-val">检测中...</span>
                                    </div>
                                    <div class="col-6 col-md-6 mb-2">
                                        <small class="text-muted">服务状态</small><br>
                                        <span id="status-dot" class="status-dot status-inactive"></span>
                                        <span id="sys-status" class="fw-bold">未知</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 mt-3 mt-md-0">
                                <div class="traffic-box">
                                    <div class="row text-center">
                                        <div class="col-6 border-end">
                                            <small class="text-muted d-block">服务器上行流量</small>
                                            <p id="trafficOutTotal" class="traffic-val text-success">0 B</p>
                                            <small id="trafficOutSpeed" class="traffic-speed text-primary">0 B/s</small>
                                        </div>
                                        <div class="col-6">
                                            <small class="text-muted d-block">服务器下行流量</small>
                                            <p id="trafficInTotal" class="traffic-val text-info">0 B</p>
                                            <small id="trafficInSpeed" class="traffic-speed text-primary">0 B/s</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div id="installed-section" class="hidden-section">
            <div class="row fade-in">
                <div class="col-md-6 mb-3">
                    <div class="card h-100">
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <h6 class="text-muted mb-0"><i class="bi bi-gear"></i> 当前配置(点击可复制对应数据)</h6>
                                <button class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#configModal"><i class="bi bi-pencil"></i> 修改</button>
                            </div>
                            <hr class="my-2">
                            <div class="row">
                                <div class="col-6 mb-2">
                                    <small class="text-muted">服务器 IP</small><br>
                                    <span id="cfg-ip" class="config-val" onclick="copyText(this.innerText, 'IP')">-</span>
                                </div>
                                <div class="col-6 mb-2">
                                    <small class="text-muted">Bind Port</small><br>
                                    <span id="cfg-bind" class="config-val" onclick="copyText(this.innerText, 'Bind Port')">-</span>
                                </div>
                                <div class="col-6 mb-2">
                                    <small class="text-muted">HTTP Port</small><br>
                                    <span id="cfg-http" class="config-val" onclick="copyText(this.innerText, 'HTTP Port')">-</span>
                                </div>
                                <div class="col-6 mb-2">
                                    <small class="text-muted">HTTPS Port</small><br>
                                    <span id="cfg-https" class="config-val" onclick="copyText(this.innerText, 'HTTPS Port')">-</span>
                                </div>
                                <div class="col-12 mb-2">
                                    <small class="text-muted">Token</small><br>
                                    <span id="cfg-token" class="config-val" onclick="copyText(this.innerText, 'Token')">-</span>
                                </div>
                            </div>
                            <hr class="my-2">
                            <div class="small text-muted">
                                <p class="mb-1"><strong>配置说明：</strong>Bind Port 为 frps 监听端口，客户端需连接此端口；HTTP/HTTPS Port 为 vhost 端口，用于 http/https 类型穿透。</p>
                                <p class="mb-0"><strong>使用说明：</strong>请确保客户端配置文件中的 server_addr、server_port 和 token 与此处配置一致。修改配置后服务将自动重启生效。</p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 mb-3">
                    <div class="card h-100">
                        <div class="card-body">
                            <h6 class="text-muted mb-2"><i class="bi bi-power"></i> frps服务控制</h6>
                            <hr class="my-2">
                            <div class="d-flex gap-2 flex-wrap mb-3">
                                <button class="btn btn-outline-success flex-fill" onclick="confirmAction('start')"><i class="bi bi-play-fill"></i> 启动</button>
                                <button class="btn btn-outline-warning flex-fill" onclick="confirmAction('stop')"><i class="bi bi-stop-fill"></i> 停止</button>
                                <button class="btn btn-outline-primary flex-fill" onclick="confirmAction('restart')"><i class="bi bi-arrow-clockwise"></i> 重启</button>
                                <button class="btn btn-outline-danger flex-fill" onclick="confirmAction('uninstall')"><i class="bi bi-trash3"></i> 卸载</button>
                            </div>
                            <h6 class="text-muted mb-2"><i class="bi bi-journal-text"></i> FRPS 运行日志</h6>
                            <pre id="frpsLogArea" class="mb-2">加载中...</pre>
                            <button class="btn btn-sm btn-outline-secondary" onclick="fetchFrpsLogs()"><i class="bi bi-arrow-clockwise"></i> 刷新</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row fade-in">
            <div class="col-12 mb-3">
                <div class="card">
                    <div class="card-body">
                        <h6 class="text-muted mb-2"><i class="bi bi-cloud-download"></i> 安装 / 重装Frps 服务端</h6>
                        <hr class="my-2">
                        <div class="row align-items-end">
                            <div class="col-md-8 mb-3">
                                <label class="form-label small mb-1">选择需要安装的frps版本</label>
                                <select id="sel-version" class="form-select form-select-sm">{{VERSION_OPTIONS}}</select>
                            </div>
                            <div class="col-md-4 mb-3">
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                    <button id="btn-install-new" class="btn btn-success btn-sm" onclick="confirmAction('install_new')"><i class="bi bi-download"></i> 开始安装frps</button>
                                    <button id="btn-upgrade-keep" class="btn btn-primary btn-sm" onclick="confirmAction('upgrade_keep')"><i class="bi bi-arrow-repeat"></i> 保留配置重装</button>
                                    <button id="btn-upgrade-reset" class="btn btn-warning btn-sm" onclick="confirmAction('upgrade_reset')"><i class="bi bi-trash"></i> 清除配置重装</button>
                                </div>
                            </div>
                        </div>
                        <small class="text-muted d-block mt-1">
                            如需查看版本说明请自行前往 <a href="https://github.com/fatedier/frp/releases" target="_blank">fatedier/frp GitHub Releases</a> 查看版本说明。
                        </small>
                    </div>
                </div>
            </div>
        </div>

        <div class="row fade-in">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h6 class="text-muted mb-2"><i class="bi bi-list-ul"></i> 面板操作记录</h6>
                        <hr class="my-2">
                        <pre id="logArea">暂无日志...</pre>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer>
        <p class="mb-1">FRP Server Manager &copy; <span id="currentYear"></span> | 基于 <a href="https://github.com/fatedier/frp" target="_blank">fatedier/frp</a> 构建 <a href="https://github.com/atanzhen/frps-web" target="_blank">github</a>  |  <a href="http://frp.atusu.cn/" target="_blank">FRP_web</a></p>
        <p class="mb-0" style="opacity:0.6;">本项目仅供学习交流使用，请遵守当地法律法规</p>
    </footer>
</div>

<!-- 修改密码模态框 -->
<div class="modal fade" id="changePwdModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header py-2 bg-primary text-white">
                <h5 class="modal-title">修改管理员密码</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label class="form-label small">当前密码</label>
                    <input type="password" id="oldPwd" class="form-control form-control-sm">
                </div>
                <div class="mb-3">
                    <label class="form-label small">新密码</label>
                    <input type="password" id="newPwd" class="form-control form-control-sm">
                </div>
                <div class="mb-3">
                    <label class="form-label small">确认新密码</label>
                    <input type="password" id="confirmPwd" class="form-control form-control-sm">
                </div>
            </div>
            <div class="modal-footer py-2">
                <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">取消</button>
                <button type="button" class="btn btn-success btn-sm" onclick="submitChangePwd()"><i class="bi bi-check-circle"></i> 确认修改</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="configModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header py-2">
                <h5 class="modal-title">修改配置</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="mb-2"><label class="form-label small">Bind Port</label><input type="number" id="inp-bind" class="form-control form-control-sm" value="7000"></div>
                <div class="row mb-2">
                    <div class="col"><label class="form-label small">HTTP Port</label><input type="number" id="inp-http" class="form-control form-control-sm" value="18080"></div>
                    <div class="col"><label class="form-label small">HTTPS Port</label><input type="number" id="inp-https" class="form-control form-control-sm" value="18443"></div>
                </div>
                <div class="mb-2">
                    <label class="form-label small">Token</label>
                    <div class="input-group input-group-sm">
                        <input type="text" id="inp-token" class="form-control">
                        <button class="btn btn-outline-secondary" onclick="genToken()">随机Token</button>
                    </div>
                    <small class="text-muted mt-1 d-block">点击“随机Token”可生成32位随机安全字符串，修改后需同步更新客户端配置。</small>
                </div>
            </div>
            <div class="modal-footer py-2">
                <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">取消</button>
                <button type="button" class="btn btn-success btn-sm" onclick="confirmAction('saveConfig')"><i class="bi bi-check-circle"></i> 保存并应用</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="confirmModal" tabindex="-1" data-bs-backdrop="static">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header py-2" id="confirmModalHeader">
                <h5 class="modal-title" id="confirmTitle">确认操作</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body" id="confirmBody">确定要执行此操作吗？</div>
            <div class="modal-footer py-2">
                <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary btn-sm" id="confirmBtn">确定</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="progressModal" tabindex="-1" data-bs-backdrop="static">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header py-2"><h5 class="modal-title" id="progressTitle">处理中</h5></div>
            <div class="modal-body text-center py-4">
                <div class="spinner-border text-primary" role="status"></div>
                <p class="mt-3 mb-0" id="progressText">正在执行操作，请稍候...</p>
            </div>
        </div>
    </div>
</div>

<div class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 1100;">
    <div id="liveToast" class="toast" role="alert">
        <div class="toast-header"><strong class="me-auto">系统提示</strong><button type="button" class="btn-close" data-bs-dismiss="toast"></button></div>
        <div class="toast-body" id="toast-body"></div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
    let progressModal, confirmModal, toastEl;
    let lastTrafficIn = 0, lastTrafficOut = 0;
    let isTrafficInit = false;
    let pendingAction = null;
    let currentSessionId = localStorage.getItem('frps_session_id');

    document.addEventListener('DOMContentLoaded', () => {
        progressModal = new bootstrap.Modal(document.getElementById('progressModal'));
        confirmModal = new bootstrap.Modal(document.getElementById('confirmModal'));
        toastEl = document.getElementById('liveToast');
        
        document.getElementById('confirmBtn').addEventListener('click', executePendingAction);
        document.getElementById('currentYear').innerText = new Date().getFullYear();

        // 检查登录状态
        checkAuth();
    });

    function checkAuth() {
        if (!currentSessionId) {
            showLoginPage();
            return;
        }
        
        fetch('/api/check_session', {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({session_id: currentSessionId})
        })
        .then(r => r.json())
        .then(data => {
            if (data.valid) {
                showMainPage();
                refreshStatus();
                setInterval(refreshStatus, 5000);
                setInterval(fetchTraffic, 2000);
                setInterval(fetchLogs, 5000);
                setInterval(fetchFrpsLogs, 5000);
            } else {
                localStorage.removeItem('frps_session_id');
                currentSessionId = null;
                showLoginPage();
            }
        })
        .catch(() => {
            showLoginPage();
        });
    }

    function showLoginPage() {
        document.getElementById('loginPage').classList.remove('hidden-section');
        document.getElementById('mainPage').classList.add('hidden-section');
    }

    function showMainPage() {
        document.getElementById('loginPage').classList.add('hidden-section');
        document.getElementById('mainPage').classList.remove('hidden-section');
    }

    function doLogin() {
        const user = document.getElementById('loginUser').value;
        const pass = document.getElementById('loginPass').value;
        const msgDiv = document.getElementById('loginMsg');
        
        if (!user || !pass) {
            msgDiv.innerText = "请输入用户名和密码";
            return;
        }
        
        msgDiv.innerText = "登录中...";
        
        fetch('/api/login', {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({username: user, password: pass})
        })
        .then(r => r.json())
        .then(data => {
            if (data.success) {
                currentSessionId = data.session_id;
                localStorage.setItem('frps_session_id', currentSessionId);
                msgDiv.innerText = "";
                showMainPage();
                refreshStatus();
                setInterval(refreshStatus, 5000);
                setInterval(fetchTraffic, 2000);
                setInterval(fetchLogs, 5000);
                setInterval(fetchFrpsLogs, 5000);
            } else {
                msgDiv.innerText = data.msg || "登录失败";
            }
        })
        .catch(err => {
            msgDiv.innerText = "网络错误";
        });
    }

    function doLogout() {
        if (currentSessionId) {
            fetch('/api/logout', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({session_id: currentSessionId})
            }).finally(() => {
                localStorage.removeItem('frps_session_id');
                currentSessionId = null;
                location.reload();
            });
        }
    }

    function submitChangePwd() {
        const oldPwd = document.getElementById('oldPwd').value;
        const newPwd = document.getElementById('newPwd').value;
        const confirmPwd = document.getElementById('confirmPwd').value;
        
        if (!oldPwd || !newPwd || !confirmPwd) {
            showToast("请填写所有字段");
            return;
        }
        
        if (newPwd !== confirmPwd) {
            showToast("两次输入的新密码不一致");
            return;
        }
        
        if (newPwd.length < 6) {
            showToast("新密码长度不能少于6位");
            return;
        }
        
        showProgress('修改密码', '正在处理...');
        
        fetch('/api/change_password', {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({
                session_id: currentSessionId,
                old_password: oldPwd,
                new_password: newPwd
            })
        })
        .then(r => r.json())
        .then(data => {
            hideProgress();
            if (data.success) {
                showToast("密码修改成功，请重新登录");
                setTimeout(() => {
                    doLogout();
                }, 1500);
            } else {
                showToast(data.msg || "修改失败");
            }
        })
        .catch(err => {
            hideProgress();
            showToast("网络错误");
        });
        
        // 关闭模态框
        let pwdModalEl = document.getElementById('changePwdModal');
        let pwdModal = bootstrap.Modal.getInstance(pwdModalEl);
        if(pwdModal) pwdModal.hide();
        
        // 清空输入
        document.getElementById('oldPwd').value = '';
        document.getElementById('newPwd').value = '';
        document.getElementById('confirmPwd').value = '';
    }

    function showProgress(title, text) {
        document.getElementById('progressTitle').innerText = title;
        document.getElementById('progressText').innerText = text;
        progressModal.show();
    }
    function hideProgress() { progressModal.hide(); }

    function showToast(msg) {
        document.getElementById('toast-body').innerText = msg;
        const toast = new bootstrap.Toast(toastEl, {delay: 3000});
        toast.show();
    }

    function copyText(text, label) {
        if(!text || text === '-') return;
        const msg = `已复制 ${label}: ${text}`;
        if (navigator.clipboard && window.isSecureContext) {
            navigator.clipboard.writeText(text).then(() => showToast(msg)).catch(() => fallbackCopy(text, msg));
        } else {
            fallbackCopy(text, msg);
        }
    }

    function fallbackCopy(text, msg) {
        const textArea = document.createElement("textarea");
        textArea.value = text;
        textArea.style.position = "fixed";
        textArea.style.left = "-9999px";
        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();
        try {
            document.execCommand('copy');
            showToast(msg);
        } catch (err) {
            showToast("复制失败，请手动复制");
        }
        document.body.removeChild(textArea);
    }

    function refreshStatus() {
        fetch('/api/status', {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({session_id: currentSessionId})
        }).then(r => r.json()).then(data => {
            if (!data.valid) {
                doLogout();
                return;
            }
            
            document.getElementById('sys-ip').innerText = data.ip;
            document.getElementById('sys-arch').innerText = data.arch;
            document.getElementById('sys-ver').innerText = data.version || 'frps未安装，请先安装';
            
            const dot = document.getElementById('status-dot');
            const statusText = document.getElementById('sys-status');
            if (data.status === 'active') {
                dot.className = 'status-dot status-active';
                statusText.innerText = '运行中'; statusText.className = 'fw-bold text-success';
            } else {
                dot.className = 'status-dot status-inactive';
                statusText.innerText = '已停止'; statusText.className = 'fw-bold text-danger';
            }

            if(data.config) {
                document.getElementById('cfg-ip').innerText = data.ip;
                document.getElementById('cfg-bind').innerText = data.config.bindPort;
                document.getElementById('cfg-http').innerText = data.config.vhostHTTPPort;
                document.getElementById('cfg-https').innerText = data.config.vhostHTTPSPort;
                document.getElementById('cfg-token').innerText = data.config.token || '(未设置)';
                
                document.getElementById('inp-bind').value = data.config.bindPort;
                document.getElementById('inp-http').value = data.config.vhostHTTPPort;
                document.getElementById('inp-https').value = data.config.vhostHTTPSPort;
                document.getElementById('inp-token').value = data.config.token;
            }

            const installedSection = document.getElementById('installed-section');
            const btnNew = document.getElementById('btn-install-new');
            const btnKeep = document.getElementById('btn-upgrade-keep');
            const btnReset = document.getElementById('btn-upgrade-reset');

            if (data.is_installed) {
                installedSection.classList.remove('hidden-section');
                btnNew.style.display = 'none';
                btnKeep.style.display = '';
                btnReset.style.display = '';
            } else {
                installedSection.classList.add('hidden-section');
                btnNew.style.display = '';
                btnKeep.style.display = 'none';
                btnReset.style.display = 'none';
            }
        }).catch(e => console.error("Status fetch error", e));
    }

    function confirmAction(action) {
        const ver = document.getElementById('sel-version').value;
        let title = "确认操作";
        let msg = "";
        let header = document.getElementById('confirmModalHeader');

        if (action === 'install_new') {
            msg = `确认要开始安装 FRPS v${ver} 吗？（清除所有配置全新安装）`;
            header.className = 'modal-header py-2 bg-info text-white';
        } else if (action === 'upgrade_keep') {
            msg = `确认要保留当前配置并重装 FRPS v${ver} 吗？`;
            header.className = 'modal-header py-2 bg-primary text-white';
        } else if (action === 'upgrade_reset') {
            msg = `⚠️ 警告：这将清除所有配置并重新安装 v${ver}！`;
            header.className = 'modal-header py-2 bg-warning text-dark';
        } else if (action === 'uninstall') {
            msg = "⚠️ 严重警告：这将完全卸载 FRPS 并删除所有相关文件！";
            header.className = 'modal-header py-2 bg-danger text-white';
        } else if (action === 'saveConfig') {
            msg = "确认保存新配置并重启服务吗？";
            header.className = 'modal-header py-2 bg-success text-white';
        } else if (['start', 'stop', 'restart'].includes(action)) {
            msg = `确认要 ${action} 服务吗？`;
            header.className = 'modal-header py-2 bg-primary text-white';
        } else {
            header.className = 'modal-header py-2';
        }

        if (!msg) return;

        document.getElementById('confirmTitle').innerText = title;
        document.getElementById('confirmBody').innerText = msg;
        pendingAction = action;
        confirmModal.show();
    }

    function executePendingAction() {
        confirmModal.hide();
        const action = pendingAction;
        const ver = document.getElementById('sel-version').value;

        if (action.startsWith('install') || action.startsWith('upgrade')) {
            let mode = 'new';
            if (action === 'upgrade_keep') mode = 'keep';
            if (action === 'upgrade_reset') mode = 'reset';
            
            let progressText = `正在下载并处理 v${ver}...`;
            showProgress('安装 FRPS', progressText);
            
            fetch('/api/install', {
                method: 'POST', 
                headers: {'Content-Type': 'application/json'}, 
                body: JSON.stringify({version: ver, mode: mode, session_id: currentSessionId})
            })
            .then(r => r.json()).then(data => {
                hideProgress();
                if (!data.valid) { doLogout(); return; }
                showToast(data.msg);
                refreshStatus();
            }).catch(err => { hideProgress(); showToast('操作失败: ' + (err.message || '网络或权限异常')); });

        } else if (action === 'saveConfig') {
            const bind = document.getElementById('inp-bind').value;
            const http = document.getElementById('inp-http').value;
            const https = document.getElementById('inp-https').value;
            const token = document.getElementById('inp-token').value;
            
            showProgress('更新配置', '正在保存配置并重启服务...');
            fetch('/api/config', {
                method: 'POST', 
                headers: {'Content-Type': 'application/json'}, 
                body: JSON.stringify({bind_port: bind, http_port: http, https_port: https, token: token, session_id: currentSessionId})
            })
            .then(r => r.json()).then(data => {
                hideProgress();
                if (!data.valid) { doLogout(); return; }
                showToast(data.msg);
                refreshStatus();
                let configModalEl = document.getElementById('configModal');
                let configModal = bootstrap.Modal.getInstance(configModalEl);
                if(configModal) configModal.hide();
            }).catch(err => { hideProgress(); showToast('操作失败: ' + (err.message || '网络异常')); });

        } else {
            showProgress('服务控制', `正在执行 ${action}...`);
            fetch('/api/service', {
                method: 'POST', 
                headers: {'Content-Type': 'application/json'}, 
                body: JSON.stringify({action: action, session_id: currentSessionId})
            })
            .then(r => r.json()).then(data => {
                hideProgress();
                if (!data.valid) { doLogout(); return; }
                showToast(data.msg);
                refreshStatus();
            }).catch(err => { hideProgress(); showToast('操作失败: ' + (err.message || '网络异常')); });
        }
    }

    function genToken() {
        const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
        let token = '';
        for (let i = 0; i < 32; i++) token += chars.charAt(Math.floor(Math.random() * chars.length));
        document.getElementById('inp-token').value = token;
    }

    function fetchTraffic() {
        fetch('/api/traffic', {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({session_id: currentSessionId})
        }).then(r => r.json()).then(data => {
            if (!data.valid) { doLogout(); return; }
            
            let totalIn = data.total_in;
            let totalOut = data.total_out;
            
            if (!isTrafficInit) {
                lastTrafficIn = totalIn;
                lastTrafficOut = totalOut;
                isTrafficInit = true;
                document.getElementById('trafficInSpeed').innerText = '0 B/s';
                document.getElementById('trafficOutSpeed').innerText = '0 B/s';
            } else {
                let speedIn = Math.max(0, totalIn - lastTrafficIn) / 2;
                let speedOut = Math.max(0, totalOut - lastTrafficOut) / 2;
                
                lastTrafficIn = totalIn;
                lastTrafficOut = totalOut;

                document.getElementById('trafficInSpeed').innerText = formatBytes(speedIn) + '/s';
                document.getElementById('trafficOutSpeed').innerText = formatBytes(speedOut) + '/s';
            }
            
            document.getElementById('trafficInTotal').innerText = formatBytes(totalIn);
            document.getElementById('trafficOutTotal').innerText = formatBytes(totalOut);
        }).catch(e => {});
    }

    function formatBytes(bytes) {
        if (bytes === 0) return '0 B';
        const k = 1024;
        const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
        const i = Math.floor(Math.log(bytes) / Math.log(k));
        return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
    }

    function fetchLogs() {
        fetch('/api/logs', {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({session_id: currentSessionId})
        }).then(r => r.text()).then(data => {
            const area = document.getElementById('logArea');
            if(data && data.trim() !== "") {
                area.innerText = data;
                area.scrollTop = area.scrollHeight;
            }
        });
    }

    function fetchFrpsLogs() {
        if(document.getElementById('installed-section').classList.contains('hidden-section')) return;
        fetch('/api/frps_logs', {
            method: 'POST',
            headers: {'Content-Type': 'application/json'},
            body: JSON.stringify({session_id: currentSessionId})
        }).then(r => r.text()).then(data => {
            const area = document.getElementById('frpsLogArea');
            if(data) {
                area.innerText = data;
                area.scrollTop = area.scrollHeight;
            }
        });
    }
</script>
</body>
</html>
"""

class FRPSHandler(BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        pass

    def send_html(self, content):
        self.send_response(200)
        self.send_header('Content-type', 'text/html; charset=utf-8')
        self.end_headers()
        self.wfile.write(content.encode('utf-8'))

    def send_json(self, data):
        self.send_response(200)
        self.send_header('Content-type', 'application/json; charset=utf-8')
        self.end_headers()
        self.wfile.write(json.dumps(data).encode('utf-8'))

    def send_text(self, text):
        self.send_response(200)
        self.send_header('Content-type', 'text/plain; charset=utf-8')
        self.end_headers()
        self.wfile.write(text.encode('utf-8'))

    def get_session_from_post(self):
        """从POST数据中提取并验证session"""
        content_len = int(self.headers.get('Content-Length', 0))
        post_data = self.rfile.read(content_len)
        try:
            data = json.loads(post_data.decode('utf-8'))
            session_id = data.get('session_id')
            if check_session(session_id):
                return True, data, session_id
            return False, data, None
        except:
            return False, {}, None

    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path
        
        if path == '/':
            options_html = ""
            for v in AVAILABLE_VERSIONS:
                options_html += '<option value="{0}">v{0}</option>\n'.format(v)
            
            py_ver = "{0}.{1}.{2}".format(sys.version_info.major, sys.version_info.minor, sys.version_info.micro)
            final_html = HTML_TEMPLATE.replace("{{VERSION_OPTIONS}}", options_html).replace("{{PY_VERSION}}", py_ver)
            self.send_html(final_html)
        else:
            self.send_response(404)
            self.end_headers()

    def do_POST(self):
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path
        
        # 公开接口：登录
        if path == '/api/login':
            content_len = int(self.headers.get('Content-Length', 0))
            post_data = self.rfile.read(content_len)
            try:
                data = json.loads(post_data.decode('utf-8'))
                username = data.get('username')
                password = data.get('password')
                
                panel_config = load_panel_config()
                pwd_hash = hashlib.sha256(password.encode()).hexdigest()
                
                if username == panel_config['username'] and pwd_hash == panel_config['password_hash']:
                    session_id = create_session(username)
                    self.send_json({'success': True, 'session_id': session_id})
                else:
                    self.send_json({'success': False, 'msg': '用户名或密码错误'})
            except Exception as e:
                self.send_json({'success': False, 'msg': '请求格式错误'})
            return

        # 公开接口：检查会话
        if path == '/api/check_session':
            valid, data, session_id = self.get_session_from_post()
            self.send_json({'valid': valid})
            return

        # 公开接口：退出
        if path == '/api/logout':
            valid, data, session_id = self.get_session_from_post()
            if valid and session_id:
                if session_id in SESSIONS:
                    del SESSIONS[session_id]
            self.send_json({'success': True})
            return

        # 公开接口：修改密码
        if path == '/api/change_password':
            valid, data, session_id = self.get_session_from_post()
            if not valid:
                self.send_json({'success': False, 'valid': False, 'msg': '未登录或会话过期'})
                return
            
            old_pwd = data.get('old_password')
            new_pwd = data.get('new_password')
            
            panel_config = load_panel_config()
            old_pwd_hash = hashlib.sha256(old_pwd.encode()).hexdigest()
            
            if old_pwd_hash != panel_config['password_hash']:
                self.send_json({'success': False, 'msg': '原密码错误'})
                return
            
            # 更新密码
            new_pwd_hash = hashlib.sha256(new_pwd.encode()).hexdigest()
            panel_config['password_hash'] = new_pwd_hash
            save_panel_config(panel_config)
            
            # 使当前会话失效（强制重新登录）
            if session_id in SESSIONS:
                del SESSIONS[session_id]
                
            self.send_json({'success': True, 'msg': '密码修改成功'})
            return

        # 以下接口需要登录验证
        valid, data, session_id = self.get_session_from_post()
        if not valid:
            self.send_json({'success': False, 'valid': False, 'msg': '未登录或会话过期'})
            return

        if path == '/api/status':
            self.send_json({
                'valid': True,
                'ip': get_ip(),
                'arch': get_arch(),
                'version': get_installed_version(),
                'is_installed': is_installed(),
                'status': get_service_status(),
                'config': read_config()
            })
        elif path == '/api/traffic':
            t_in, t_out = get_traffic_stats()
            self.send_json({'valid': True, 'total_in': t_in, 'total_out': t_out})
        elif path == '/api/logs':
            logs = ""
            if os.path.exists(LOG_FILE):
                try:
                    with open(LOG_FILE, 'r', encoding='utf-8') as f:
                        lines = f.readlines()
                        logs = "".join(lines[-50:])
                except: pass
            self.send_text(logs)
        elif path == '/api/frps_logs':
            self.send_text(get_frps_logs())
        elif path == '/api/install':
            version = data.get('version', '').strip()
            mode = data.get('mode')
            
            if not version:
                self.send_json({'success': False, 'valid': True, 'msg': '未选择版本'})
                return

            log_operation('INSTALL', '版本 {0} ({1})'.format(version, mode), 'START')
            
            old_config = None
            if mode == 'keep':
                old_config = read_config()
            
            if mode == 'reset' or mode == 'new':
                if os.path.exists(CONFIG_FILE): os.remove(CONFIG_FILE)
                run_cmd([get_sysctl_path(), "stop", SERVICE_NAME])
                bin_path = os.path.join(INSTALL_DIR, "frps")
                if os.path.exists(bin_path): os.remove(bin_path)
            else:
                run_cmd([get_sysctl_path(), "stop", SERVICE_NAME])
                bin_path = os.path.join(INSTALL_DIR, "frps")
                if os.path.exists(bin_path): os.remove(bin_path)

            success, msg = download_and_install(version)
            if not success:
                log_operation('INSTALL', '版本 ' + version, 'FAILED')
                self.send_json({'success': False, 'valid': True, 'msg': msg})
                return

            if mode == 'reset' or mode == 'new':
                token = ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(32))
                write_config('7000', '18080', '18443', token)
            elif old_config:
                write_config(old_config['bindPort'], old_config['vhostHTTPPort'], old_config['vhostHTTPSPort'], old_config['token'])
            
            setup_systemd()
            
            success, msg = control_service('restart')
            log_operation('INSTALL', '版本 ' + version, 'SUCCESS' if success else 'FAILED')
            
            new_version = get_installed_version() or "未知版本"
            if success:
                if mode == 'new': final_msg = "全新安装完成，当前版本: v{0}".format(new_version)
                elif mode == 'keep': final_msg = "保留配置重装完成，当前版本: v{0}".format(new_version)
                elif mode == 'reset': final_msg = "清除配置重装完成，当前版本: v{0}".format(new_version)
                else: final_msg = "安装完成，当前版本: v{0}".format(new_version)
            else:
                final_msg = "文件安装成功(v{0})，但服务启动失败: {1}".format(new_version, msg)
                
            self.send_json({'success': success, 'valid': True, 'msg': final_msg})

        elif path == '/api/config':
            bind_port = data.get('bind_port')
            http_port = data.get('http_port')
            https_port = data.get('https_port')
            token = data.get('token')

            log_operation('CONFIG', '更新端口与Token', 'START')
            
            if os.path.exists(CONFIG_FILE):
                shutil.copy(CONFIG_FILE, CONFIG_FILE + '.bak')
            
            write_config(bind_port, http_port, https_port, token)
            success, msg = control_service('restart')
            
            if not success:
                if os.path.exists(CONFIG_FILE + '.bak'):
                    shutil.copy(CONFIG_FILE + '.bak', CONFIG_FILE)
                    control_service('restart')
                log_operation('CONFIG', '更新端口与Token', 'ROLLBACK')
                self.send_json({'success': False, 'valid': True, 'msg': '配置应用失败，已回滚。原因: ' + msg})
            else:
                log_operation('CONFIG', '更新端口与Token', 'SUCCESS')
                self.send_json({'success': True, 'valid': True, 'msg': '配置更新并重启成功'})

        elif path == '/api/service':
            action = data.get('action')
            action_cn = {'start': '启动', 'stop': '停止', 'restart': '重启', 'uninstall': '卸载'}.get(action, action)
            
            if action not in ['start', 'stop', 'restart', 'uninstall']:
                self.send_json({'success': False, 'valid': True, 'msg': '无效操作'})
                return
            
            log_operation('SERVICE', action_cn + '服务', 'START')
            success, msg = control_service(action)
            log_operation('SERVICE', action_cn + '服务', 'SUCCESS' if success else 'FAILED')
            self.send_json({'success': success, 'valid': True, 'msg': msg})
        else:
            self.send_response(404)
            self.end_headers()

if __name__ == '__main__':
    if os.geteuid() != 0:
        print("\033[0;31m[ERROR]\033[0m 此脚本必须以 root 权限运行！")
        print("请使用: sudo python3 frps_panel.py")
        sys.exit(1)
    
    # 启动会话清理线程
    cleanup_thread = threading.Thread(target=cleanup_sessions, daemon=True)
    cleanup_thread.start()
    
    port = 8080
    server = HTTPServer(('0.0.0.0', port), FRPSHandler)
    print("\033[0;32m[INFO]\033[0m FRPS Web 管理面板已启动")
    print("\033[0;32m[INFO]\033[0m Python 版本: {0}".format(sys.version.split()[0]))
    print("\033[0;32m[INFO]\033[0m 访问地址: http://0.0.0.0:{0}".format(port))
    print("\033[0;32m[INFO]\033[0m 默认账号: admin, 默认密码: admin8888")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n[INFO] 面板已停止")
        server.server_close()